name: model_fetch_firestore_json_files
description: A lazy load BLoC wrapper for local JSON files in Firestore format
version: 0.5.6
repository: https://github.com/alexeyinkin/dart-model-fetch

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  firestore_api_converter: ^0.1.0
  meta: ^1.7.0
  model_fetch: ^0.5.6
  model_interfaces: ^0.3.0
  path: ^1.8.3

dependency_overrides:
  #model_fetch: { path: '../model_fetch' }

dev_dependencies:
  total_lints: ^3.1.0
