name: model_fetch
description: A lazy load wrapper for your data source.
version: 0.7.0
repository: https://github.com/alexeyinkin/dart-model-fetch

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  meta: ^1.7.0
  model_interfaces: ^0.3.1
  rxdart: '>=0.27.3 <0.29.0'

dev_dependencies:
  total_lints: ^3.4.0
