name: model_fetch
description: A lazy load BLoC wrapper for your data source.
version: 0.5.6
repository: https://github.com/alexeyinkin/dart-model-fetch

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  meta: ^1.7.0
  model_interfaces: ^0.3.1
  rxdart: ^0.27.3

dev_dependencies:
  total_lints: ^3.1.0
