name: model_fetch_firestore
description: A lazy load BLoC wrapper for Firestore collections.
version: 0.1.1
homepage: https://github.com/alexeyinkin/dart-model-fetch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.13
  meta: ^1.7.0
  model_fetch: ^0.1.0
