name: model_fetch_firestore
description: A lazy load wrapper for Firestore collections.
version: 0.7.0
repository: https://github.com/alexeyinkin/dart-model-fetch

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  cloud_firestore: '>=4.1.0 <7.0.0'
  collection: ^1.16.0
  flutter: { sdk: flutter }
  meta: ^1.7.0
  model_fetch: ^0.7.0
  model_interfaces: ^0.3.0

dependency_overrides:
  #common_macros: { path: ../../dart-common-macros }
  #model_fetch: { path: '../model_fetch' }

dev_dependencies:
  total_lints: ^3.4.0
