name: model_fetch_firestore
description: A lazy load BLoC wrapper for Firestore collections.
version: 0.6.0
repository: https://github.com/alexeyinkin/dart-model-fetch

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: '>=4.1.0 <6.0.0'
  collection: ^1.16.0
  common_macros: ^0.1.0-7.dev
  flutter: { sdk: flutter }
  macro_util: ^0.1.0-12.dev
  macros: ^0.1.0-main.5
  meta: ^1.7.0
  model_fetch: ^0.6.0
  model_interfaces: ^0.3.0

dependency_overrides:
  #common_macros: { path: ../../dart-common-macros }
  #model_fetch: { path: '../model_fetch' }

dev_dependencies:
  total_lints: ^3.4.0
