name: model_fetch_flutter
description: Flutter widgets to build lazy load lists from model_fetch package.
version: 0.1.0
homepage: https://github.com/alexeyinkin/dart-model-fetch

environment:
  sdk: '>=2.16.2 <3.0.0'
  flutter: ">=2.10.5"

dependencies:
  model_fetch: ^0.1.0
  visibility_detector: 0.2.2 # https://github.com/google/flutter.widgets/issues/354

  flutter:
    sdk: flutter
