name: model_fetch_flutter
description: Flutter widgets to build lazy load lists from model_fetch package.
version: 0.6.0
repository: https://github.com/alexeyinkin/dart-model-fetch

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter: { sdk: flutter }
  model_fetch: '>=0.5.0 <0.7.0'
  visibility_detector: '>=0.3.3 <5.0.0'

dependency_overrides:
  #model_fetch: { path: '../model_fetch' }

dev_dependencies:
  total_lints: ^3.1.0
